# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-06 07:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=500)),
                ('created_time', models.DateField(auto_now=True)),
                ('email', models.EmailField(max_length=255)),
                ('sex', models.CharField(choices=[('1', 'boy'), ('2', 'girl')], max_length=1)),
                ('birth', models.DateField(blank=True, default='1994/06/06')),
                ('public', models.BooleanField(default=True)),
                ('important', models.BooleanField(default=False)),
                ('allow', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=500)),
                ('created_time', models.DateField(auto_now=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comments.Comment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
