# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-06 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='message',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='message',
            new_name='content',
        ),
        migrations.AlterField(
            model_name='comment',
            name='sex',
            field=models.CharField(max_length=1),
        ),
    ]
