# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-04 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20180102_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='reply_to',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
