# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-06 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20171106_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='sex',
            field=models.CharField(choices=[('1', 'boy'), ('2', 'girl')], max_length=1),
        ),
    ]
