# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-06 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_auto_20171106_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='reply',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
