# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-14 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauth_ex',
            name='type',
            field=models.CharField(choices=[('1', 'github'), ('2', 'qq'), ('3', 'weibo')], max_length=1),
        ),
    ]
