# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-23 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hobby',
            field=models.TextField(blank=True, default='无', max_length=200),
        ),
    ]
