# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-16 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_emailverify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverify',
            name='send_time',
            field=models.DateField(auto_now=True),
        ),
    ]
